### ISSUE TITLE
Community Exchange Introduction/Tracking

### ISSUE THREAD

**Issue by ericdrosado** [rajat2502/StandNote#12]
👋 Hi @PragatiVerma18,

I am your GitHub mentor for the GitHub Education, [Community Exchange](https://airtable.com/shrRJ3AvEZQohOdGV) (CX) project. I'll be collaborating with you on preparing your repo for CX. 

You mentioned in your submission that you wanted to submit a `Learn + Collaborate` repo. This means that you would like to teach students, step by step, how to build this project as well as invite other students to collaborate and add features to this repo. I will generate issues, which will provide guidance on how to prepare your repo for a `Learn + Collaborate` CX submission on June 1, 2022.

This issue will serve as a tracking issue to track all issues related to CX. I recommend creating a new branch for every issue and opening a pull request to track changes so we can effectively collaborate with each other and merge changes when you and I feel like those changes are ready to be merged on your primary branch. 

Your repo is currently in great shape, so I don't believe we will have to do too much to get your repo ready for a CX submission 😄 

If you have any questions or concerns, please feel free to leave a comment on this issue or any of the other issues that are generated. 

I look forward to working with you :octocat: 

## Issues
- [x] https://github.com/rajat2502/StandNote/issues/13
- [x] https://github.com/rajat2502/StandNote/issues/14
- [x] https://github.com/rajat2502/StandNote/issues/15
- [x] https://github.com/rajat2502/StandNote/issues/16
- [x] https://github.com/rajat2502/StandNote/issues/17

**Comment by ericdrosado** [comment]
@PragatiVerma18, I noticed that `rajat2502` is the current owner of the repository. In order to submit a repository to Community Exchange this repository would have to be under your handle or `rajat2502` will need to submit it. Are any of these options possible? 

Of course if `rajat2502` submits the repository I would still add you as a private beta user for your hard work.

**Comment by PragatiVerma18** [comment]
Hey @ericdrosado, @rajat2502 has filled up the airtable form for submitting this repo to Community Exchange. Can you please check it once?

**Comment by ericdrosado** [comment]
I've added @rajat2502 to the list of users who will receive access to the private beta. @PragatiVerma18 and @rajat2502  you will both be added as private beta users when the invitation is extended. 🎉

**Comment by PragatiVerma18** [comment]
Thanks a lot @ericdrosado 😄

**Comment by ericdrosado** [comment]
@PragatiVerma18 @rajat2502 you are all set. Thank you for completing the issues. 

Early next week, I will extend an invite to you to submit your repository to CX. Please keep this issue open for now.

**Comment by PragatiVerma18** [comment]
Thanks @ericdrosado for all the help and support, looking forward to the CX invitation. :smile:

**Comment by ericdrosado** [comment]
@PragatiVerma18 @rajat2502 you have been given access to [Community Exchange](https://education.github.com/globalcampus/exchange)

@PragatiVerma18 you will be sent an email with instructions.
